# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages_robocup_ssl_wrapper_legacy.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'messages_robocup_ssl_wrapper_legacy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from strategy_bridge.pb import messages_robocup_ssl_detection_pb2 as messages__robocup__ssl__detection__pb2
from strategy_bridge.pb import messages_robocup_ssl_geometry_legacy_pb2 as messages__robocup__ssl__geometry__legacy__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)messages_robocup_ssl_wrapper_legacy.proto\x12\x19RoboCup2014Legacy.Wrapper\x1a$messages_robocup_ssl_detection.proto\x1a*messages_robocup_ssl_geometry_legacy.proto\"{\n\x11SSL_WrapperPacket\x12&\n\tdetection\x18\x01 \x01(\x0b\x32\x13.SSL_DetectionFrame\x12>\n\x08geometry\x18\x02 \x01(\x0b\x32,.RoboCup2014Legacy.Geometry.SSL_GeometryData')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_robocup_ssl_wrapper_legacy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SSL_WRAPPERPACKET']._serialized_start=154
  _globals['_SSL_WRAPPERPACKET']._serialized_end=277
# @@protoc_insertion_point(module_scope)
